### PR TITLE
reading FedACHdir.txt

### PR DESCRIPTION
**Pull request by bkmoovio**
reading FedACHdir.txt

### CODE REVIEW

**Comment by bkmoovio** [comment]
Closes #29

**Comment by adamdecaf** [comment]
I assume you'll add env variables for the file paths?

**Comment by bkmoovio** [comment]
I'm not sure I am following, the files are in that directory.  It is currently not configurable.  It existed in the repo as such.

**Comment by adamdecaf** [comment]
Those paths work for local dev `go run .`, but when fed is deployed on a server we'll need to customize the storage locations for the files it's reading. Not a big deal to worry about now, just when we deploy fed.

**Comment by bkmoovio** [comment]
so when it is deployed on the server the files won't be in fed/data?    If it's using go mod and go mod vendor it will be a there as a dependency correct?

**Comment by bkmoovio** [comment]
And to clarify, for the API I modeled after OFAC which is great, but then I kept iterating by pulling things out because what it seems is needed for FED is less complex than what is needed for OFAC.  If over time we need to add the additional features in, that is fine.

**Comment by adamdecaf** [comment]
Right. Fed is a lot less complex of an app, so that's fine. 

I was planning on deploying Fed with the files managed independently in persistent storage for that exact usecase. We could name files `FedACHdir-yyyy-mm-dd.txt` (or whatever the bank wants) and point the Fed instance at that. `FEDACH_FILE=/data/FedACHdir-yyyy-mm-dd.txt`.

**Comment by bkmoovio** [comment]
The file name to be read can be the same and the archived file(s) contain the date.  Similar to OFAC the file names to be downloaded/read are sdn.csv, alt.csv, add.csv,  Archived files have a date association

**Pull request merged**
